name: Build and Push Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: docker build --file Dockerfile --tag ghcr.io/tpcypher/front/app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/tpcypher/front/app:latest